global_defs {
  vrrp_version 3
  max_auto_priority
}

vrrp_instance instance1 {
  state MASTER
  interface eth0
  virtual_router_id 1
  priority 100
  advert_int 1
  virtual_ipaddress {
    192.168.12.30/24        
  }
}
